name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
    
    - name: Install Chrome for Selenium
      uses: browser-actions/setup-chrome@v1
      with:
        chrome-version: stable
      id: setup-chrome
    
    - name: Install ChromeDriver
      uses: nanasess/setup-chromedriver@v2
    
    - name: Set up virtual environment
      run: uv venv
    
    - name: Install dependencies
      run: |
        uv pip install -e .
        uv pip install pytest
    
    - name: Set Chrome binary path
      run: |
        echo "CHROME_BIN=${{ steps.setup-chrome.outputs.chrome-path }}" >> $GITHUB_ENV
    
    - name: Run tests
      run: |
        source .venv/bin/activate
        python -m pytest test.py -v --tb=short
      env:
        # Set display for headless Chrome
        DISPLAY: :99
    
    - name: Run tests with coverage (Python 3.11 only)
      if: matrix.python-version == '3.11'
      run: |
        source .venv/bin/activate
        uv pip install pytest-cov
        python -m pytest test.py --cov=main --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to CodeCov (Python 3.11 only)  
      if: matrix.python-version == '3.11'
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
